name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Pull latest changes (to prevent conflicts)
        run: git pull https://Chintan06:$HF_TOKEN@huggingface.co/spaces/Chintan06/code-assistant main --rebase
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://Chintan06:$HF_TOKEN@huggingface.co/spaces/Chintan06/code-assistant main
