jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set Git User Identity
        run: |
          git config --global user.email "chintan672003@gmail.com"
          git config --global user.name "Chintan0607"
      - name: Pull latest changes (to prevent conflicts)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git pull https://Chintan06:$HF_TOKEN@huggingface.co/spaces/Chintan06/code-assistant main --rebase
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://Chintan06:$HF_TOKEN@huggingface.co/spaces/Chintan06/code-assistant main
